[기능] 등록된 클래스 검색 기능 (#52)
YAPP-Github/20th-ALL-Rounder-Team-2-BE pull request #103
Opened 2022-07-01 00:18 UTC by Park-Young-Hun

## 작업 내용 설명
- 등록된 클래스 검색 기능

## 주요 변경 사항
- Keyword로 검색하면 카테고리 이름과 클래스 제목 기반으로 검색

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없는가?
- [x] 생성된 코드에 Javadoc 주석을 추가 하였는가?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었는가?

## 관련 이슈
- resolved #52

@NaLDo627 @Park-Young-Hun

2022-07-01 01:47 UTC, NaLDo627 requested changes
수고하셨습니다. 코멘트 확인해주시고, 부족한 테스트 보충해주세요!

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/LectureImageMapperTest.java
> +                        .build()
테스트 dto 만들때 TestLectureImageDtoFactory처럼 대리 생성자를 만드는게 이후에 편할 것 같습니다.

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapper.java
>      LectureInformation toEntity(LectureInformationDto lectureInformationDto);
toEntity에 대한 테스트가 없던데, 체크 한 번 해주세요.

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationSearchService.java
> +    }
repository 상으로 Page를 리턴하지 않고, 직접 paginate한 이유가 있을까요?
또한 해당 메서드가 public으로 선언되어 있는 이유가 궁금합니다.

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationSearchService.java
> +        }
여기서 이게 필요한지 잘 모르겠습니다. 카테고리 이름으로 찾는 메서드는 따로 만드는게 낫지 않을까요?

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureInformationControllerTest.java
> +    }
이게 "마케팅" 이라는 키워드로 카테고리 이름으로 찾게 된건지, topic 혹은 introduce 기준으로 찾게 된건지 알기가 애매합니다. 경우의 수 추가해주면 좋겠네요.

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/util/TestLectureInformationEntityFactory.java
> +                            .id(entityId)
이러면 LectureImage의 id가 모두 entityId 하나로 통일되지 않나요?

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationService.java
> +    }
해당 메서드의 테스트가 보이지 않습니다.

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepository.java
> +    List<LectureInformation> findAllByTopicContainingAndIsActiveOrderByIdDesc(@Param("topic") String topic, boolean isActive);
여기 역시 마찬가지로, 별도로 작성된 Repository 메서드들에 대해서는 특히 테스트 작성 부탁드립니다!!

2022-07-01 01:47 UTC, NaLDo627 commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/CategoryRepository.java
> +    Optional<Category> findByCategoryNameAndIsActive(String categoryName, boolean isActive);
이렇게 별도로 작성된 Repository 메서드들에 대해서는 특히 테스트 작성 부탁드립니다!!

2022-07-01 01:48 UTC, NaLDo627 commented
@Park-Young-Hun

2022-07-01 08:18 UTC, Park-Young-Hun commented on knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/LectureImageMapperTest.java
> +                        .build()
넵 추가 완료했습니다!

2022-07-01 12:32 UTC, Park-Young-Hun commented on knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapper.java
>      LectureInformation toEntity(LectureInformationDto lectureInformationDto);
추가했습니다!

2022-07-01 12:45 UTC, Park-Young-Hun commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationSearchService.java
> +    }
private으로 바꾸겠습니다!!
제가 구현한 로직상 repository에서 각각 결과를 얻어오는 것이 아니라 키워드를 검색했을 때  "카테고리 이름 기반 검색한 결과"와 "클래스 제목 기반 검색한 결과"를 합쳐줘야 되기 때문에 검색결과를 만들어주고 중복도 제거한 뒤 paginate 해주었습니다.

화면에서 보면 검색할때 케이스를 나누는 것이 아닌 키워드로 한번 검색하기 때문에 저렇게 구현했습니다!

2022-07-01 16:02 UTC, Park-Young-Hun commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationSearchService.java
> +        }
분리해서 리팩토링 진행했습니다!

2022-07-01 16:48 UTC, Park-Young-Hun commented on knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureInformationControllerTest.java
> +    }
클래스 제목기반, 카테고리 이름기반 각각 1회씩 테스트하도록 변경했습니다!

2022-07-01 16:51 UTC, Park-Young-Hun commented on knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/util/TestLectureInformationEntityFactory.java
> +                            .id(entityId)
해당부분도 수정했습니다! 감사합니다!

2022-07-01 17:05 UTC, Park-Young-Hun commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationService.java
> +    }
테스트 추가 완료했습니다!

2022-07-01 18:01 UTC, Park-Young-Hun commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepository.java
> +    List<LectureInformation> findAllByTopicContainingAndIsActiveOrderByIdDesc(@Param("topic") String topic, boolean isActive);
작성 완료했습니다!

2022-07-01 18:01 UTC, Park-Young-Hun commented on knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/CategoryRepository.java
> +    Optional<Category> findByCategoryNameAndIsActive(String categoryName, boolean isActive);
리뷰 사항 모두 반영 완료했습니다! 상세한 리뷰 감사드립니다!!

2022-07-02 03:24 UTC, NaLDo627 approved these changes
수고 많으셨습니다!

2022-07-02 05:11 UTC, merged